version: '3.8'
services:
  blazorapp1:
    build: .
    ports:
      - "8080:80"  
    depends_on:
      - sqlserver  

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest  
    environment:
      SA_PASSWORD: "YourStrongPass123!" 
      ACCEPT_EULA: "Y"  
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql 

volumes:
  sqlvolume:  